
name: 'sampledatastack'
version: '0.1'
profile: 'sampledatastack'
config-version: 2

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "docs/sampledatastack"
clean-targets:
    - "docs"
    - "docs/sampledatastack"
    - "dbt_modules"
    - "logs"

models:
  sampledatastack:
      materialized: table
      staging:
        materialized: view
